spring.config.import=optional:file:.env
spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://fuzailk05:fuzzu2103@evway.w6j1xby.mongodb.net/EvWay?appName=EvWay
spring.mongodb.uri=mongodb+srv://fuzailk05:fuzzu2103@evway.w6j1xby.mongodb.net/EvWay?appName=EvWay
server.port=8081
groq.api.key=${GROQ_API_KEY:YOUR_GROQ_API_KEY}
