spring.config.import=optional:file:.env[.properties]
spring.application.name=backend
spring.data.mongodb.uri=${MONGODB_URI}
spring.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8081}
groq.api.key=${GROQ_API_KEY:YOUR_GROQ_API_KEY}
ocm.api.key=${OCM_API_KEY:YOUR_OCM_API_KEY}
