spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://fuzailk05:fuzzu2103@evway.w6j1xby.mongodb.net/EvWay?retryWrites=true&w=majority&appName=EvWay
server:
  port: 8080

